loggers:
  root:
      level: DEBUG
server:
  port: 8081
  servlet:
spring:
  batch:
    jdbc:
      isolation-level-for-create: DEFAULT
    initialize-schema: ALWAYS
    job:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect